### ISSUE TITLE
Re-upload stream from day 0

### ISSUE THREAD

**Issue by bomcon123456** [JamesPerlman/TurboNeRF#20]
What an awesome project, sadly I know this too late, I've search your twitch account but it only has from day 16 on, can u double check and reupload from day 0 if possible? That would be really helpful for us to rewatch. Thank you!!

**Comment by JamesPerlman** [comment]
Ahhh unfortunately Twitch removes them after some time, I believe.  I do have a dropbox with all the original OBS clips though!  They are sorted by date.  Inside each dated folder, you will find a subfolder that contains the OBS clips (raw recordings usually split into 1 hour segments).  Enjoy!

https://www.dropbox.com/home/ZeroToNeRF/NeRF%20From%20Scratch
